### ISSUE TITLE
No need to have a test script to run tests

### ISSUE THREAD

**Issue by facuspagnuolo** [nventuro/crafty#1]
I know it is hard to know, but from the [truffle 4.0.0 release](https://github.com/trufflesuite/truffle/releases/tag/v4.0.0) changelog:

> **Caveat**: For backwards compatibility, if you have an existing Truffle project with a development or test network specified in your truffle.js file, Truffle will use those networks instead of this new built-in blockchain. To take full advantage of this feature, remove or rename the development and test networks from your truffle.js file. If you're just using the TestRPC for development, consider using the new truffle develop instead!

That said, you just need to remove the `development` network from the `truffle.js` config file and change the npm test command to work with truffle.

**Comment by nventuro** [comment]
Huh, it actually was _that_ easy. I probably configured the network before doing any testing, which is why I never noticed that feature. Anyway, it's good to know there's a way to configure the testing blockchain, if needed.
