### ISSUE TITLE
Provide access to the ERC20 CraftableTokens from the UI

### ISSUE THREAD

**Issue by nventuro** [nventuro/crafty#17]
[CraftableToken](https://github.com/nventuro/crafty/blob/master/contracts/CraftableToken.sol)s are ERC20 compliant, so it'd be interesting for the players to easily access their addresses, allowing trade, etc.

**Comment by spalladino** [comment]
Sounds like a good idea. Maybe a _copy address_ button, or something like that...?

**Comment by nventuro** [comment]
That's why I was thinking, a copy to clipboard button next to each token.
