### ISSUE TITLE
Make the UI consistent and prettier

### ISSUE THREAD

**Issue by nventuro** [nventuro/crafty#18]
The UI is a bit of a mess right now, making it both ugly and difficult to use.

Areas to improve include:
* The inventory list consists of barebones HTML `<ul>` and `<il>` tags, while the recipes list is a Bootstrap list.
* The 'pending' badges have tooltips, but they are slow to appear and not super useful. These could be improved, and more elements could benefit from tooltips.
* There's almost no 'reloading inventory' feedback, other than the latest block changing.
* The overall color scheme is dull
* The toasts have a link to [etherscan](http://etherscan.io/), but they go away too quickly, and require clicking on the transaction hash, instead of anywhere inside them.

**Comment by spalladino** [comment]
Agree on consistency, no need to worry about prettiness at this stage. I'd keep an eye especially on the sync between the pending/confirmed transactions and the current inventory, to make sure that whenever a transaction is confirmed, the inventory is immediately updated (from a user's perspective).

Also, the badge representing "number of pending transactions" is not intuitive for the user (regardless of their speed to appear). Let's consider an alternative way to represent them.

**Comment by nventuro** [comment]
> I'd keep an eye especially on the sync between the pending/confirmed transactions and the current inventory, to make sure that whenever a transaction is confirmed, the inventory is immediately updated (from a user's perspective).

I'm not sure why new blocks arrive much later (10-15 seconds) after the transaction promises fulfill, the `Mint` events might be a better way of knowing when a craft call's result has been reflected on the inventory.

Regarding the badges, I thought of adding an actions log, including transaction status, cost, etc. WDYT?

**Comment by spalladino** [comment]
> I'm not sure why new blocks arrive much later (10-15 seconds) after the transaction promises fulfill, the Mint events might be a better way of knowing when a craft call's result has been reflected on the inventory.

I wouldn't rule out optimistic updates for the UI, so you don't need to rely on events or new blocks. On the other hand, keep in mind that reorgs are possible (and a pain to handle). If it helps, take a look at the philosophy behind [gnarly](https://medium.com/xlnt-art/solving-severe-asynchronicity-with-gnarly-51f5310e5543) (though I've never used it myself).

> Regarding the badges, I thought of adding an actions log, including transaction status, cost, etc. 

Could work, but I'd make sure to show the info right next to where the user expects to see it. If the user has clicked a button requesting +1 wood, then show this info right where the user will go and look (his wood supply possibly).

**Comment by nventuro** [comment]
> If it helps, take a look at the philosophy behind gnarly (though I've never used it myself).
Nice, thanks. Seems like there's nothing Matt isn't involved in!

What worries me about optimistic updates is allowing the player to queue crafting items, and then having them fail due to lack of ingredients if one of the transactions fail (craft wood fails -> craft sword fails -> craft tri-sword fails). I'll give it a try and see how I can make it work.
