### ISSUE TITLE
Improve landing page - game description

### ISSUE THREAD

**Issue by nventuro** [nventuro/crafty#19]
Currently, the only game description is a short paragraph on the readme, which is packed with unrelated (installation, deployment, etc) information. A more thorough and newbie-friendly description (maybe including ideas for future content?) should be added somewhere that is accessible from the front-end, such as a another page, the repo's wiki, etc.

**Comment by spalladino** [comment]
Agree! Let's add it as part of the app, instead of the wiki, so users are presented with this info as soon as they enter the application. It could be either a header, or a landing page that then redirects to the game.

**Comment by nventuro** [comment]
Closed by 236b84c9cfcda5be833c52ee1d4e75f05a0ce893
