### ISSUE TITLE
JS Improvements

### ISSUE THREAD

**Issue by facuspagnuolo** [nventuro/crafty#4]
Some JS improvements

## Modularize the app in modules
Now, the whole JS behavior of the app is held between the `app.js` and the `layout.js` file. It would be good to model separate models to encapsulate different logic improving their abstraction and their readability. 

Moreover, it would be good to consolidate a single way of modeling these behaviors. JavaScript gives you the chance to have single functions, plain old JS objects, classes, etc. Having one way of doing things makes clear on how to collaborate 😉 

For example, the `layout.js` file includes the error handling logic. This behavior could be extracted to a module itself. 

## Place JS dependencies within `<head>`
Some JS scripts are loaded at the end of the `index.html` file, I understand the purpose. You can use `async` though.

## Separate lib files from project files
All the JS files are placed within the `js` folder, please move them to custom folders such as `lib` and `app` folders or so.

**Comment by nventuro** [comment]
Regarding asynchronous loading of the scripts, wouldn't [`defer`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) make more sense here, since some scripts depend on others (like JQuery) having been already loaded?

**Comment by nventuro** [comment]
The changes proposed by @spalladino [here](https://github.com/nventuro/crafty/pull/12#issuecomment-369603055) should be included when tackling this issue.
