### ISSUE TITLE
Move constants to a separate module

### ISSUE THREAD

**Issue by facuspagnuolo** [nventuro/crafty#5]
Would be good to investigate if [`dotenv`](https://www.npmjs.com/package/dotenv) can work with gh-pages.

**Comment by nventuro** [comment]
Apparently `dotenv` only works on the server, and the way to replicate its behaviour on the browser is using [`dotenv-webpack`](https://www.npmjs.com/package/dotenv-webpack), which of course requires [`webpack`](https://webpack.js.org/). I am not sure it's worth it to add `webpack` to the project just for this, so I may factor out those constants by putting them in a `config.json` file.
